### ISSUE TITLE
Quick comments III

### ISSUE THREAD

**Issue by RohanAlexander** [krishnak30/US_elections#10]
- R is appropriately cited (1/1)
	- Great.
- Data are appropriately cited (1/1)
	- Great.
- Class paper (1/1)
	- Great.
- LLM usage is documented (1/1)
	- Great.
- Title (1/2)
	- "...Analysis for Battleground..." should be "...Analysis of Battleground..."
- Author, date, and repo (2/2)
	- Great.
- Abstract (4/4)
	- Great.
- Introduction (2/4)
	- First paragraph and fourth paragraph are great (although you should also telegraph the appendix).
	- Second is okay. Third is bad.
- Estimand (0/1)
	- What you say is your estimand isn't an estimand. Just briefly review the estimand paper mentioned in the notes.
	- Also, please split it into a separate paragraph.
- Data (6/10)
	- Don't include data cleaning here. Move it to an appendix. 
	- Please make sure that every observation of every variable in your model is somewhere in this data section. For instance, Figure 1, you only show four pollsters - that's fine if you only use four pollsters, but then in Table 2 you talk about five. So ATM I don't think you've plotted everything.
- Measurement (2/4)
	- The foundational thing we are trying to measure is what someone is going to do on Election Day based on their opinion some time before election day. I don't really see this in your measurement section. I understand that you've tried to talk about the measurement of, say, recency, and that's fine, but you've not really hit how we go from some phenomena in the world to an entry in this dataset.
- Model (8/10)
	- Reduce the number of decimal places, especially in AIC/BIC
- Results (5/10)
	- Reduce the number of decimal places in Table 4. Absolutely not more than 2, maybe even one or none. Read the King paper and then think about it and decide.
	- You don't actually show the model results anywhere. Please just add a modelsummary table or graph.
- Discussion (3/10)
	- Limited points made so far. Don't forget to come back to this.
- Prose (0/6)
	- Please don't use words/phrases that I asked you not to.
	- Typos throughout. Copy/paste to Word and then fix whatever it identifies in your Quarto.
	- If you use a word ending in "ly" then think about whether you ~really~ need it.
- Cross-references (1/1)
	- Great
- Captions (1/2)
	- Don't say "Figure" or "Directed Acyclic Graph", etc, in the caption.
- Graphs/tables/etc (2/4)
	- You don't need both titles and caption. Just move whatever is in the title into the start of the caption.
	- Figure 5 is so nice.
- Idealized methodology (8/10)
	- Great.
- Idealized survey (3/4)
	- Great.
- Pollster methodology overview and evaluation (8/10)
	- Great.
- Referencing (0/4)
	- Fix the capitalization of R packages.
- Commits (2/2)
	- Great.
- Sketches (0/2)
	- Couldn't find this.
- Simulation (3/4)
	- Be more sophisticated.
- Tests-simulation (0/4)
	- Not done.
- Tests-actual (0/4)
	- Not done.
- Parquet (1/1)
	- Great.
- Reproducible workflow (2/4)
	- Don't forget to comment on and close all Issues after you address them.
	- Be consistent in your approach to filenames e.g. https://github.com/krishnak30/US_elections/tree/main/other/llm_usage - some capitals at the start and some not.
- Miscellaneous (2/3)
	- Figure 7
	- DAG

**Comment by DeniseChang9** [comment]
Thank you for your valuable feedback! We've brought corrections to the repo.
