### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [krishnak30/US_elections#4]
- "Predicting the 2024 U.S. Presidential Elections using the Method of Polls of Polls" - "Elections" should be "Election". Don't include " using the Method of Polls of Polls"
- "Project 538" - it's not "Project".
- Remove unused files and folders e.g. https://github.com/krishnak30/US_elections/blob/main/scripts/00-simulate_data.py
- It doesn't make sense to load both tidyverse and dplyr. When you load tidyverse you get dplyr, so just load tidyverse. Load both makes it look like you don't know what you're doing.
- Why is there paper.html?
- Cross-reference the different bits in the introduction when you telegraph them.
- Numbering is wrong e.g. 2 then 2.0.1. You need a 2.1 or you need to change 2.0.1 to 2.1.
- Measurement is not specific enough. This could refer to almost anything.
- Citation for @dplyr didn't resolve. In any case you shouldn't cite dplyr, you should cite tidyverse (see earlier comment).
- Don't say "The histogram".
- Figure does not have a caption.
- "Forcasting" is a typo. It should be "Forecasting". If the reader can't trust you to spell the word how can they trust you to implement the method!
- Captions need more detail.
- Figure 2 does not show the data.
- Figure 3 probably needs alpha.
- R not cited.
- Capitalization not correct in reference e.g. "u.s.". Use double braces

**Comment by DeniseChang9** [comment]
Thank you for the feedback! Corrections made : )
