### ISSUE TITLE
Peer Review 1 - Group 148

### ISSUE THREAD

**Issue by Tanmay-Shinde** [krishnak30/US_elections#6]
**Opening statement summary**:
This paper uses a poll-of-polls approach to predict the voter support percentage for Kamala Harris in the 2024 U.S. presidential election. It aggregates multiple polls to reduce individual bias and improve accuracy and uses a regression model to predict her overall support to be 47.78%. The study emphasizes the importance of factors such as pollster quality and recency to refine the forecast, providing a more reliable estimate of electoral outcomes.

**Strong positive points**:
- The paper starts with a strong and concise abstract and introduces the topic and overall methodology used very well in the introduction. 
- The estimand is clearly stated in the introduction and a list of all predictor variables is provided. The authors give a detailed explanation of data cleaning process and provides a thorough summary statistics of all variables of interest
- The model is explained and justified very well in the Model section and predictions as well as results are clearly stated with the relevant equations and tables included in the paper. the discussion section summarizes not only the results of the study but also addresses the strengths and weaknesses, making it a well-rounded anlysis.
- The project repository is also well structured and the authors have included all relevant components of a statistical study as defined by the [Workflow Components](https://tellingstorieswithdata.com/01-introduction.html#workflow-components) of "Telling Stories With Data" (Alexander, 2023). The authors have included all relevant sketches, plan for the study, their raw datasets, analysis data as well as a detailed LLM usage statement and survey-related files.

**Critical improvements needed**
1. Measurement section: Consider making the measurement section more detailed and specific to how different polling organizations conduct these polls and how and what (mathematical or statistical) methods they use to convert people's answers and opinions to a point in the dataset. Also consider explaining how FiveThirtyEight assigns numeric_grade and pollscore values to each polling organization to make your measurement section more technical and detailed.

2. Tests for Analysis Data: Currently, you do not have a script to test your analysis data which is a crucial part of the data processing process for this paper. Do add tests for the cleaned data to ensure consistency and reliability of the dataset. You can use a similar suite of tests as you did for your simulated data.

3. Cite R: Another crucial aspect of the paper is to cite all resources and tools you used to perform the data processing and analysis. Do not forget to include the citation in your Data section!

4. Commit Messages: The commit messages on the repository currently are very general and vague, consider writing more detailed and informative commit messages that say exactly what changes were made to the code and in which files to ensure that you have a more detailed record. This is a good feature of GitHub that it allows you to revert to a specific state of your project by reversing all the commits you made after that; informative commits make it easier to do so.

Other than these, there is no other aspect of the paper or project repository that need critical changes.

**Suggestions for improvement:**

Please consider:
1. Changing "polls of polls" to "poll of polls" in the tiltle as well as in the first sentence of your abstract, same in the README file
2. Include all relevant sketches in an "other/sketches" folder
3. Remove paper.html file from the repo
4. Remove paper/paper_files/libs - I think these are rendering files related to you paper, there is no need to include these in the repo
5. Highlight the data limitations in your discussion to mention the lack of availability of data over a longer time period and how that might affect results.
6. Discuss potential alternative datasets in the Data section and why they were not used (refer to rubric)

**Evaluation:**
The analysis and report is detailed and thorough, the project repository is well-structured and the workflow is highly reproducible. However, you would greatly benefit from making the changes mentioned above to improve the overall grade for your paper.

Estimated mark:
0/126 ~ 0% (**Note that this is only because R is not cited in your paper, a detailed marking is provided below**)

Rubric:
- R citation - 0/1
- Data citation - 1/1
- Does not look like class paper - 1/1
- LLM usage - 1/1
- Title - 1/2 (subtitle has a little too much detail)
- Author, date, and repo - 2/2
- Abstract - 4/4
- Introduction - 4/4
- Estimand - 1/1
- Data - 8/10
- Measurement - 2/4
- Model - 8/10 (linear model is used which might not be a strong model in pedicting voter support)
- Results - 6/10 
- Discussion - 10/10
- Prose - 4/10 (some noticable typos - chatgpt can point these out for you if u give it the pdf)
- Cross-references - 0/1
- Captions - 0/2
- Graphs/tables/etc - 4/4
- Idealized methodology - 10/10
- Idealized survey - 4/4
- Pollster methodology overview and evaluation - 10/10
- Referencing - 0/4
- Commits - 0/2
- Sketches - 0/2
- Simulation - 4/4
- Simulation tests - 4/4
- Actual tests - 0/4
- Parquet - 1/1
- Reproducibility - 2/4
- Miscellaneous - 2/3

**Additional Comments:**
The score is calculated based on the given rubric. Overall, the study excels in most grading criterias, but falls short in certain smaller criterias. The analysis is carried out effectively using the available data and everything is structured properly. This is a greta first draft for your paper, and only needs certain improvements in the smaller aspects of the rubric.

~~ This peer review is up to date as of October 23rd, 2024 12:24 pm ~~

**Comment by DeniseChang9** [comment]
Thanks so much for the review! Updates were made base on your suggestions : )
