### ISSUE TITLE
Peer Review from Group 71

### ISSUE THREAD

**Issue by RayanAlim** [krishnak30/US_elections#8]
### Summary
This paper forecasts voter support for Kamala Harris in the 2024 U.S. election through a "polls of polls" approach. Overall, the work is well-structured, the following feedback provides point to improve the paper:

### Strong positive points
* The model is well-justified and the methodology is robust.
* The writing is clear and concise, avoiding unnecessary jargon.
* Model well explained
* ReadMe is clear and the repo is well organized 

### Critical improvements needed
- Fix cross-referencing 
- Add captions to all figures and tables 
- Remove unused files
- Remove paper.html
- Remove usage.txt in llm usage file

### Suggestions for improvement
- Elaborate on background information and why this matters in the introduction. 
- Mention data used in abstract 
- No sketches
- Consider briefly defining "polls of polls" for readers unfamiliar with the term. This could help set the stage for your methodology
- You provide a good overview of data cleaning, but consider including more details about how you handled outliers or any anomalies in the dataset

### Evaluations

R cited: 0/1 
- Although you say you used R, it is not cited properly.

Data cited: 1/1
- Data is cited

Class paper: 1/1
- No indication its a class paper 

LLM usage documented: 1/1

Title: 1/2
- Subtitle too long and could do without the results and methodology, since it is mentioned in the abstract. 

Author, date, and repo: 2/2
- All present

Abstract: 3/4
- Good Overview, mention what data it uses

Introduction: 2/4
- Structure of the paper included
- Lacks depth around why this matters and tells us about the world.

Estimand: 1/1
- States the estimated

Data: 10/10
- Good data introduction and explanation
- Great Visualizations and tables 

Measurement: 3/4
- I think more detail can be added here

Model: 8/10
- Included mathematical notation
- Defined variables
- Include figure captions for Model section
- Limitations of model and other possible avenues
- Address model validation more

Results: 8/10
- Explain the 

Discussion: 6/10

Prose: 4/6

Cross-references: 0/1
- Some are broken

Captions: 1/2
- A couple are missing 

Graphs/tables/etc: 1/2
- Some figures missing captions 
- Discuss all figures you include more

Idealized methodology: 6/10
- Discuss limitations and tradeoffs 

Idealized Survey: 4/4

Pollster methodology: 10/10

Referencing: 3/4
- References added
- But not much supporting literature, can add more to analysis

**Commits: 2/2**
- Good commit messages, appropriate to changes made

Sketches: 0/2

Simulation: 4/4
- Save simulated data as parquet

Tests-Simulation: 4/4

Tests-actual: 4/4

Parquet: 0/1
- Data not saved as a parquet

Reproducible workflow: 2/4
- Save as parquet in simulated data

Miscellaneous: 2/3

Estimated overall mark 94/126 (But realistically a 0 since R is not cited)

Any other comments:
This paper is already pretty solid and the analysis is strong, adding more depth to why this matters and context in the introduction section will improve its quality. Also just making sure to go over all the points of the rubric

**Comment by DeniseChang9** [comment]
Thank you, corrections made
