### ISSUE TITLE
Quick comments II

### ISSUE THREAD

**Issue by RohanAlexander** [krishnak30/US_elections#9]
Please:
- Don’t say “linear regression” in your subtitle. 
- Don’t have two decimal places of results in your subtitle – it doesn’t make sense given the uncertainty of the model.
- Cross reference the rest of the paper in the telegraphing paragraph of your introduction.
- Make your measurement subsection less general. What you have here could apply to basically anything! Why don’t you reference some papers or other work and show off your knowledge?
- Add captions to your figures. 
- Make your table captions (and figure captions when you add them) more detailed.
- Don't say things like “The histogram” in the text.
- Plot the actual data - using boxplots does’t show the data - and every variable in your model needs to be plotted in the data section.
- Change your modelling approach which is incorrectly focused on statistical significance. For instance you mention that California is significant. But what we want to use the model for is to average out the polls. 
- Make the appendices less general and and show off your knowledge of surveys or sampling.
- Fix the capitalization in the references section.

**Comment by DeniseChang9** [comment]
Thank you! Corrections made.
